name: cfbestip

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # enbale windows linux darwin freebsd on amd64, arm64
        goos: [android]
        goarch: [arm64]
       
        include:
          # include linux on arm5, arm6, arm7, 386, riscv64
          - goos: linux
            goarch: arm64
          - goos: android
            goarch: arm64
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23 # 可以指定编译使用的 Golang 版本
          binary_name: "cfbestip" # 可以指定二进制文件的名称
          ldflags: -s -w -X "main.version=${{ github.ref_name }}"
          md5sum: false
